### ISSUE TITLE
please answer reddit question

### ISSUE THREAD

**Issue by hoebat** [arrdem/oxcart#28]
I'm looking to get some feedback about oxcart here: https://www.reddit.com/r/Clojure/comments/aluoar/what_is_the_status_of_some_of_the_clojure_static/. It'd be really great to understand what has been done and why the project was abandoned.

**Comment by arrdem** [comment]
I believe I've written about all this previously. Provided some links. https://www.reddit.com/r/Clojure/comments/aluoar/what_is_the_status_of_some_of_the_clojure_static/efloo0k/
